name: Build and Test

on: [push, pull_request]

jobs:

  test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install building dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --use-feature=2020-resolver -r requirements.txt
    - name: Build package
      run: tools/1-build.sh
      shell: bash
    - name: Uninstall building dependencies
      # Need a clean environment to verify if everything are good
      run: pip uninstall --use-feature=2020-resolver -r requirements.txt -y
    - name: Install the built package
      run: pip install -U assets/dist/tflite2onnx-*.whl
    - name: Testing
      run: pytest
    # - name: SSH via Ngrok if fail
    #   if: ${{ failure() }}
    #   env:
    #     # Find token in: https://dashboard.ngrok.com/get-started/setup
    #     NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
    #     NGROK_LOCAL_PASS: ${{ secrets.NGROK_LOCAL_PASS }}
    #   run: tools/open-github-connection.sh
    # - name: Live instance if fail
    #   if: ${{ failure() }}
    #   run: sleep 1h
